package com.pauljean.soapwebserver.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-19T23:13:46.773+01:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://service.soapwebserver.pauljean.com/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "sayHelloByName", targetNamespace = "http://service.soapwebserver.pauljean.com/", className = "com.pauljean.soapwebserver.service.SayHelloByName")
    @ResponseWrapper(localName = "sayHelloByNameResponse", targetNamespace = "http://service.soapwebserver.pauljean.com/", className = "com.pauljean.soapwebserver.service.SayHelloByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHelloByName(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.soapwebserver.pauljean.com/", className = "com.pauljean.soapwebserver.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.soapwebserver.pauljean.com/", className = "com.pauljean.soapwebserver.service.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello()
;
}
